coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

flags:
  frontend:
    paths:
      - frontend/src/
    carryforward: true
  backend:
    paths:
      - backend/src/
    carryforward: true

ignore:
  - "frontend/src/test/"
  - "frontend/src/assets/"
  - "backend/src/tests/"
  - "backend/prisma/"
  - "**/*.config.js"
  - "**/*.test.js"
  - "**/*.test.jsx"
